global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jms-bridge'
    static_configs:
      - targets: ['jms-bridge:9122']
    metrics_path: /actuator/prometheus

  - job_name: 'consumer-java'
    static_configs:
      - targets: ['consumer-java:9123']
    metrics_path: /actuator/prometheus

  - job_name: 'consumer-node'
    static_configs:
      - targets: ['consumer-node:9124']
    metrics_path: /metrics

  - job_name: 'client-flask'
    static_configs:
      - targets: ['client-flask:5000']
    metrics_path: /metrics

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
